load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "schema_idl",
    srcs = ["schema_idl.go"],
    importpath = "go.idol-lang.org/idol/schema_idl",
    visibility = ["//visibility:public"],
    deps = ["//idol"],
)
