load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "idoltext",
    srcs = [
        "idoltext.go",
        "idoltext_encode.go",
    ],
    importpath = "go.idol-lang.org/idol/encoding/idoltext",
    visibility = ["//visibility:public"],
    deps = ["//idol"],
)
